#!/bin/bash

mkdir -p data/davis_baseball_64x64/
cd data/davis_baseball_64x64/
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/00000.jpg
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/00001.jpg
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/00002.jpg
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/00003.jpg
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/00004.jpg
mkdir vnlb
cd vnlb
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/000.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/001.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/002.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/003.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/004.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/bsic_000.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/bsic_001.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/bsic_002.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/bsic_003.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/bsic_004.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/deno_000.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/deno_001.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/deno_002.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/deno_003.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/deno_004.tif
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/measures-bsic
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/measures-deno
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/sigma.txt
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/tvl1_000_b.flo
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/tvl1_000_f.flo
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/tvl1_001_b.flo
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/tvl1_001_f.flo
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/tvl1_002_b.flo
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/tvl1_002_f.flo
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/tvl1_003_b.flo
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/tvl1_003_f.flo
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/tvl1_004_b.flo
wget https://github.com/gauenk/files/raw/master/pyvnlb/davis_baseball_64x64/vnlb/tvl1_004_f.flo
cd ../../../
